config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :ab, controller: 'accounting_books'
  resources :categories

  root :to => "accounting_books#index"

end

app/models/accounting_book.rb
class AccountingBook < ActiveRecord::Base
	validates_presence_of :consume_date
	validates_presence_of :description
	validates_presence_of :cost
	validates_presence_of :main_class_id
	validates_presence_of :subclass_id
	validates_presence_of :consume_way_id

	belongs_to :main_class
	belongs_to :subclass
	belongs_to :third_class
	belongs_to :consume_way

	delegate :name, :to=>:main_class, :prefix=>true, :allow_nil=>true
	delegate :name, :to=>:subclass, :prefix=>true, :allow_nil=>true
	delegate :name, :to=>:third_class, :prefix=>true, :allow_nil=>true
	delegate :name, :to=>:consume_way, :prefix=>true, :allow_nil=>true

end

app/models/consume_way.rb
class ConsumeWay < ActiveRecord::Base
	has_many :account_books
end

app/models/main_class.rb
class MainClass < ActiveRecord::Base
	has_many :subclasses
	has_many :accounting_books
end

app/models/subclass.rb
class Subclass < ActiveRecord::Base
	belongs_to :main_class
	has_many :third_classes
	has_many :account_books

end

app/models/third_class.rb
class ThirdClass < ActiveRecord::Base
	belongs_to :subclass
	has_many :account_books
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/accounting_books_controller.rb
class AccountingBooksController < ApplicationController
	before_action :set_ab, :only => [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

	def index
		set_abs

		if params[:edit_id] == nil
			@ab = AccountingBook.new
		else
			@ab = AccountingBook.find(params[:edit_id])
			hash = params[:accounting_book];
		end

		respond_to do |format|
			format.html
			format.js
			format.json
		end

	end

	def new
		@ab = AccountingBook.new
		render ab_index_url
	end

	def create
		@ab = AccountingBook.new(ab_params)

		if @ab.save
			flash[:notice]="新增成功"

			redirect_to ab_index_url
		else
			set_abs
			render :action => :index
		end
	end

	def show
		respond_to do |format|
			format.json {
					# render :json=>@ab.to_json
					render :json=> {:id =>@ab.id, 
													:consume_date => @ab.consume_date,
													:description => @ab.description, 
													:cost => @ab.cost,
													:main_class => @ab.main_class.name,
													:subclass => @ab.subclass.name,
													:third_class => @ab.third_class.name,
													:consume_way => @ab.consume_way.name,
													:note => @ab.note
												}

				}
		end

	end

	def edit
		redirect_to ab_index_url(:edit_id => @ab.id)
	end

	def update
		if @ab.update(ab_params)
			flash[:warning]="修改成功"
			redirect_to ab_index_url
		else
			set_abs
			render :action => :index			
		end
	end

	def destroy
		@ab.destroy
		flash[:warning]="移除成功"
		redirect_to ab_index_url
	end

	private

	def ab_params
		params.require(:accounting_book).permit(:consume_date, :description, :cost, :main_class_id, 
												:subclass_id, :third_class_id, :consume_way_id, :note)
	end

	def set_ab
		@ab = AccountingBook.find(params[:id])
	end

	def set_abs
		@abs = AccountingBook.order('consume_date DESC').page(params[:page]).per(5)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

	def configure_permitted_parameters
	devise_parameter_sanitizer.for(:sign_up) << :username
	devise_parameter_sanitizer.for(:account_update) << :username
	end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@cats = MainClass.all
		@main_cat = MainClass.new
		@subcat = Subclass.new
		@third_cat = ThirdClass.new
	end

	def create
		@main_cat = MainClass.new()
		@subcat = Subclass.new
		@third_cat = ThirdClass.new
		redirect_to categories_path
		
	end

	def update

		redirect_to categories_path
	end

private

	def params_filter
		params.require(:main_class).permit(:name)
		params.require(:subclass)
		params.require(:third_cat)
		
	end

end

app/helpers/accounting_books_helper.rb
module AccountingBooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/accounting_books/edit.html.erb
<%= link_to "回到首頁",ab_index_path %>
<%= form_for @ab, :url => ab_path(@ab), :method => :patch do |form|%>
	<%= render :partial => 'form', :locals => { :form => form } %>	
	<%= form.submit "更新" %>
		
<% end %>

app/views/accounting_books/index.html.erb
<div class="row">
	<div class="col-md-6">
		<h1>我的個人記帳簿</h1>		
	</div>

<div><%# f.label :username %><br />
  <%# f.text_field :username %></div>

 
<% if current_user %>
          <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
          <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %>
      <% end %>


<!-- message  -->


		<% if flash[:notice] %>
			<div class="col-md-4 alert alert-success"><h4><%=flash[:notice]%></h4></div>
		<%end%>

		<% if flash[:warning] %>
			<div class="col-md-4 alert alert-warning"><h4><%=flash[:warning]%></h4></div>
		<%end%>

</div>
<div class="row">
	<div class="col-md-12">
		<%= link_to "新增類別",categories_path%>
	</div>
</div>

<!--- index and edit pages -->

<% url_hash = if @ab.new_record?
						    { :url => ab_index_path } 
						  else
						 		{ :url => ab_path(@ab), :method => "patch" }
						  end
%>

<div class="row">
	<div class="col-md-12">
	<%= form_for @ab, url_hash do |form|%>
		<table class="table table-condensed form-table">
			<tr class="ab_row">
				<td>消費時間	</td>
				<td>描述		</td>
				<td>費用		</td>
				<td>主項目	</td>
				<td>副項目	</td>
				<td>其他項目 </td>
				<td>消費方式 </td>
				<td>備註</td>				
			</tr>
			<tr class="ab_row">	
				<td class="ab-col-date">
					<%= form.date_field :consume_date,value: Date.today%>
				</td>	
				<td class="ab-col-desc">
					<%= form.text_field :description, :class => (@ab.errors[:description].any?)? "field-error" : ""  %>
				</td>		
				<td class="ab-col-cost">
					<%= form.number_field :cost, :class => (@ab.errors[:cost].any?)? "field-error" : ""  %> 		
				</td>
				<td class="ab-col-main"><%= form.collection_select(:main_class_id, MainClass.all, :id, :name)%>
				<td class="ab-col-sub"><%= form.collection_select(:subclass_id, Subclass.all, :id, :name) %></td>
				<td class="ab-col-third"><%= form.collection_select(:third_class_id, ThirdClass.all, :id, :name) %></td>		
				<td class="ab-col-consume"><%= form.collection_select(:consume_way_id, ConsumeWay.all, :id, :name) %></td>		
				<td class="ab-col-note"><%= form.text_field :note %></td>
				
				<% if @ab.new_record? %>
					<td colspan="3"><%=form.submit "新增項目", :class => "btn btn-primary" %>
					</td>		
				<% else %>
					<td><%= form.submit '更新', :class => 'btn btn-warning'%></td>
					<td><%= link_to '取消', ab_index_path, :class => 'btn btn-info cancel-update'%></td>
					<!-- <td colspan="3"><%#button_to "更新", "#", :onclick => "$('#new_accounting_book').submit()", :class => "glyphicon glyphicon-plus" %></td>		 -->
				<% end %>						
				</tr>
		</table>
	<% end %><!-- form -->

	</div><!-- col-md-12 -->
</div><!-- row -->


<!-- data content -->
<div class="row data-row">
	<div class="col-md-12 data-table">
		<table class="table table-striped table-hover table-condensed text-center">
			<tr>
				<td>編號		</td>
				<td>消費時間	</td>
				<td>描述		</td>
				<td>費用		</td>
				<td>主項目	</td>
				<td>副項目	</td>
				<td>其他項目 </td>
				<td>消費方式 </td>
				<td>備註</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>

			<% @abs.each_with_index do |ab, i| %>
				
				<tr class="ab_row <%= (@ab == ab)? "danger" : "" %>">

					<td class="ab-col-index"><%= i+1 %>              </td>
					<td class="ab-col-date"><%=ab.consume_date %>    </td>
					<td class="ab-col-desc"><%=ab.description %>     </td>
					<td class="ab-col-cost"><%=ab.cost %> 			 </td>
					<td class="ab-col-main"><%=ab.main_class_name %>   </td>
					<td class="ab-col-sub"><%=ab.subclass_name %>     </td>
					<td class="ab-col-third"><%=ab.third_class_name %>  </td>
					<td class="ab-col-consume"><%=ab.consume_way_name %>  </td>
					<td class="ab-col-note"><%=ab.note %>      		</td>
					<td class="ab_col-btn1">
						<%if @ab.new_record? %>
						<%=link_to "顯示", ab_path(ab), :class=>"btn btn-info btn-show-ab", :"data-toggle"=>"modal", :"data-target"=>"#myModal", :type=>"button",:remote=>true,:data =>{:type=>:json} %> 
						<% end %>
					</td>

					<td class="ab_col-btn2">
						<%if @ab.new_record? %>
						<%=link_to "修改", edit_ab_path(ab), :class=>"btn btn-warning" %>
						<% end %>
					</td>

					<td class="ab_col-btn3">
						<%if @ab.new_record? %>
						<%=button_to "移除", ab_path(ab), :method => :delete, data: { confirm: "Are you sure?"},  :class =>"btn btn-danger" %> 
						<% end %>
					</td>
				</tr>
			<% end %><!-- @abs.each -->					

		</table>
	</div>
</div>

<%= paginate @abs %>


<div id="ab_area"></div>


<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal"> -->
  <!-- Launch demo modal -->
<!-- </button> -->

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"> description</h4>
      </div>
      <div class="modal-body">
			<table class='table table-hover'>
				<tr><td>消費日期 </td><td>  consume_date </td></tr>
				<!-- <tr><td>描述		</td><td>  description  </td></tr> -->
				<tr><td>費用    </td><td>  cost 			</td></tr>
				<tr><td>主項目   </td><td>  main_class	</td></tr>
				<tr><td>副項目   </td><td>  subclass		</td></tr>
				<tr><td>其他項目  </td><td>  third_class	</td></tr>
				<tr><td>消費方式  </td><td>  consume_way	</td></tr>
				<tr><td>備註     </td><td>  note			</td></tr>
			</table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

app/views/accounting_books/new.html.erb
<%= link_to "回到首頁",ab_index_path %>
<%= form_for @ab, :url => ab_index_path do |form|%>
	<%= render :partial => 'form', :locals => { :form => form } %>	
	<%= form.submit "Create" %>
		
<% end %>

app/views/accounting_books/show.html.erb
<p>你的資料表</p>
<table>
	<tr><td>消費時間	</td><td><%= @ab.consume_date %>   </td></tr>
	<tr><td>描述		</td><td><%= @ab.description %>    </td></tr>
	<tr><td>主項目	</td><td><%= @ab.main_class_id %>  </td></tr>
	<tr><td>副項目	</td><td><%= @ab.subclass_id %>    </td></tr>
	<tr><td>其他項目 </td><td><%= @ab.third_class_id %> </td></tr>
	<tr><td>消費方式 </td><td><%= @ab.consume_way_id %> </td></tr>
	<tr><td>備註     </td><td><%= @ab.note %>           </td></tr>
</table>

<%= link_to "回主列表", ab_index_path %>

app/views/categories/index.html.erb
<%= link_to "回到記帳簿", ab_index_path%>

<%# form_for @ab, url_hash do |form|%>
<%= form_for @main_cat, :url=>categories_path, :method=>'get' do |f|  %>
	<%= f.label :name, "主項目" %>
	<%= f.text_field :name, :class => "form-control" %>

	<%= f.label 'subclass', "次項目" %>
	<%= text_field_tag 'subclass'%>

	<%= f.label 'third_cat', "其他項目" %>
	<%= text_field_tag 'third_cat'%>


	<%= f.submit "更新" %>	
<%= button_to 'abc', category_path(1), :method=>'post'%>
<% end %>





<!---
<div class="row">
	<div class="col-md-12">
		<table class="table">
			<th>
				

			</th>

		</table>

	</div>


</div>

-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>記帳簿</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>